# Application
spring.application.name=traffic-monitoring-backend
server.port=8080

# Database H2
spring.datasource.url=jdbc:h2:mem:trafficdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.trace=false
spring.h2.console.settings.web-allow-others=false

# JWT Configuration
jwt.secret=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
jwt.access-token-expiration=3600000
jwt.refresh-token-expiration=86400000

# LTA API
lta.api.key=9fb1e30d7d60b6c2174412ac4dd8fd27

# Logging
logging.level.org.springframework.security=DEBUG
logging.level.com.traffic=DEBUG