#spring.application.name=traffic-monitoring-backend

# Server
server.port=8080

# Database H2
spring.datasource.url=jdbc:h2:mem:trafficdb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# JWT Configuration
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000

# LTA DataMall API
lta.api.key=9fb1e30d7d60b6c2174412ac4dd8fd27
lta.api.base-url=https://api.data.gov.sg/v1/transport